In [2]:
# Implementación del método de Gauss Simple
from numpy import*
a = [[2,3,7],[-2,5,6],[8,9,4]]
b = [3,5,8]
n = len(b)
c = zeros([n,n+1])
for i in range(n):
    for j in range(n):
        c[i][j] = a[i][j]
    c[i][n] = b[i]
for e in range(n):
    t = c[e][e]
    for j in range(e,n+1):
        c[e][j] = c[e][j]/t
    for i in range(e+1,n):
        t = c[i][e]
        for j in range(e,n+1):
            c[i][j] = c[i][j] - t*c[e][j]
x = zeros([n,1])
x[n-1] = c[n-1][n]
for i in range(n-2,-1,-1):
    s = 0
    for j in range(i+1,n):
        s = s+c[i][j] * x[j]
    x[i] = c[i][n] - s
#return x
print(x)

[[-0.05555556]
 [ 0.91503268]
 [ 0.05228758]]


In [9]:
#solución de un Sistema lineal: Gauss con pivoteo
from numpy import*
a = [[2,3,7],[-2,5,6],[8,9,4]]
b = [3,5,8]
n = len(b)
c = zeros([n,n+1])
for i in range(n):
    for j in range(n):
        c[i][j] = a[i][j]
    c[i][n] = b[i]
for e in range(n):
    p = e
    for i in range(e+1,n):
        if abs(c[i][e]) > abs(c[p][e]):
            p = i
    for j in range(e,n+1):
        t = c[e][j]
        c[e][j] = c[p][j]
        c[p][j] = t
    t = c[e][e]
    if abs(t) < 1e-10:
        print()
    for j in range(e,n+1):
        c[e][j] = c[e][j]/t
    for i in range(e+1,n):
        t = c[i][e]
        for j in range(e,n+1):
            c[i][j] = c[i][j] - t*c[e][j]
x = zeros([n,1])
x[n-1] = c[n-1][n]
for i in range(n-2,-1,-1):
    s = 0
    for j in range(i+1,n):
        s = s+c[i][j]*x[j]
    x[i] = c[i][n]-s
print(x)


[[-0.05555556]
 [ 0.91503268]
 [ 0.05228758]]


In [12]:
# Sistema tridiagonal (algoritmo de Thomas)
a = [0,2,6,9]
b = [7,-8,4,8]
c = [5,1,3,0]
d = [6,5,7,8]
n = len(d)
w = [b[0]]
g = [d[0]/w[0]]
for i in range(1,n):
    w = w+[b[i]-a[i]*c[i-1]/w[i-1]]
    g = g+[(d[i]-a[i]*g[i-1])/w[i]]
x = []
for i in range(n):
    x = x+[0]
x[n-1] = g[n-1]
for i in range(n-2,-1,-1):
    t = x[i+1]
    x[i] = g[i]-c[i]*t/w[i]
print(x)

[0.7402402402402403, 0.16366366366366353, 4.8288288288288275, -4.432432432432431]


In [14]:
from numpy import*
a = [[2,3,7],[-2,5,6],[8,9,4]]
b = [3,5,8]
linalg.det(a)

-306.0

In [15]:
x = dot(linalg.inv(a),b)
print(x)

[-0.05555556  0.91503268  0.05228758]


In [17]:
#Con la opción set_printoptions(precisión = d)
set_printoptions(precision = 4)
print(x)

[-0.0556  0.915   0.0523]


In [19]:
x = linalg.solve(a,b)
print(x)

[-0.0556  0.915   0.0523]


In [ ]:
linalg.norm(a,1)
linalgnorm(a,inf)
linalg.cond(a,1)
linalg.cond(a,inf)